//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoNgay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoNgay()
        {
            this.NhanLuc_BaoCao = new HashSet<NhanLuc_BaoCao>();
            this.ViTriBom_BaoCao = new HashSet<ViTriBom_BaoCao>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
        public Nullable<int> NguoiBaoCaoId { get; set; }
        public string MayBomId { get; set; }
        public string CongTrinhId { get; set; }
        public string KhachHangId { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual CongTrinh CongTrinh { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MayBom MayBom { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanLuc_BaoCao> NhanLuc_BaoCao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViTriBom_BaoCao> ViTriBom_BaoCao { get; set; }
    }
}
