//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CkpEntities : DbContext
    {
        public CkpEntities()
            : base("name=CkpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoNgay> BaoCaoNgay { get; set; }
        public virtual DbSet<CongTrinh> CongTrinh { get; set; }
        public virtual DbSet<DonGiaBom> DonGiaBom { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<MayBom> MayBom { get; set; }
        public virtual DbSet<NguoiLienHe> NguoiLienHe { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<ViTriBom> ViTriBom { get; set; }
        public virtual DbSet<NhanLuc_BaoCao> NhanLuc_BaoCao { get; set; }
        public virtual DbSet<ViTriBom_BaoCao> ViTriBom_BaoCao { get; set; }
    }
}
