//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongTrinh()
        {
            this.BaoCaoNgay = new HashSet<BaoCaoNgay>();
            this.DonGiaBom = new HashSet<DonGiaBom>();
        }
    
        public string Id { get; set; }
        public string SoHopDong { get; set; }
        public string TenCongTrinh { get; set; }
        public string DiaChi { get; set; }
        public string KhachHangId { get; set; }
        public Nullable<System.DateTime> NgayKyHD { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
        public Nullable<int> NguoiPhuTrachId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoCaoNgay> BaoCaoNgay { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonGiaBom> DonGiaBom { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
