//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonGiaBom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonGiaBom()
        {
            this.ViTriBom_BaoCao = new HashSet<ViTriBom_BaoCao>();
        }
    
        public int Id { get; set; }
        public string CongTrinhId { get; set; }
        public string TenDonGia { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> DonGiaVAT { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<double> MinKlgBomCan { get; set; }
        public Nullable<double> MinKlgBomTinh { get; set; }
        public Nullable<int> CC1 { get; set; }
        public Nullable<int> TongCC2 { get; set; }
        public Nullable<int> PhanTramBackCC2 { get; set; }
        public Nullable<int> TienBackCC2 { get; set; }
        public Nullable<int> NetCC2 { get; set; }
        public Nullable<int> TongThu { get; set; }
        public Nullable<int> TongVAT { get; set; }
        public Nullable<int> TongThuVAT { get; set; }
        public Nullable<int> TongCC { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string CongThuc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual CongTrinh CongTrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViTriBom_BaoCao> ViTriBom_BaoCao { get; set; }
    }
}
