//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiLienHe
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string Chucvu { get; set; }
        public string SoDienThoai { get; set; }
        public string GhiChu { get; set; }
        public string KhachHangId { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySuaCuoi { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
