//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanLuc_BaoCao
    {
        public int Id { get; set; }
        public Nullable<int> BaoCaoId { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public Nullable<double> KhoiLuongBom { get; set; }
        public Nullable<int> DonGiaKhoi { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
