//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkpApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViTriBom_BaoCao
    {
        public int Id { get; set; }
        public Nullable<int> BaoCaoId { get; set; }
        public Nullable<int> ViTriId { get; set; }
        public Nullable<int> Tang { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public string DonVi { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> DonGiaVat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> DonGiaId { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
        public virtual DonGiaBom DonGiaBom { get; set; }
        public virtual ViTriBom ViTriBom { get; set; }
    }
}
